name: emergencyresponsetool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_app_name: ^0.1.0
  flutter_launcher_icons: ^0.9.2
  google_fonts: ^6.2.0
  lottie: ^1.1.0
  fluttertoast: ^8.0.8
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/applogo.png"
  min_sdk_android: 30

  flutter_app_name:
    name: "A mobile based"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/banners/banner_emergency.jpg
    - assets/banners/online_mode.jpeg
    - assets/banners/policebanners.jpg
    - assets/lottie/running.json
    - assets/icons/applogo.png
